# Generated by Django 5.0.4 on 2024-04-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null='False')),
                ('prenom', models.CharField(max_length=50, null='False')),
                ('tel', models.IntegerField(max_length=12, null='False')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null='False')),
                ('prenom', models.CharField(max_length=50, null='False')),
                ('niveau', models.CharField(max_length=50, null='False')),
                ('tel', models.IntegerField(max_length=12, null='False')),
            ],
        ),
    ]
