# Generated by Django 5.0.4 on 2024-05-02 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapport_de_stage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='prenom',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personnel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='tel',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='niveau',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='tel',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200)),
                ('rapport_pdf', models.FileField(upload_to='media/')),
                ('date_defendu', models.DateTimeField()),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rapport_de_stage.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rapport_de_stage.etudiant')),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rapport_de_stage.rapport')),
            ],
        ),
    ]
