# Generated by Django 5.0.4 on 2024-05-02 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapport_de_stage', '0002_remove_etudiant_nom_remove_etudiant_prenom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('faculte', models.CharField(max_length=50)),
                ('option', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='departement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rapport_de_stage.departement'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='departement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rapport_de_stage.departement'),
        ),
    ]
